---
functional:
  - Пользователь должен иметь возможность регистрации и входа в систему, в том числе через социальные сети или сервисы (например, Github, Discord).
  - Пользователь должен иметь возможность менять имя и редактировать свой профиль.
  - Пользователь должен иметь возможность создавать игру с выбором языка программирования и различными модификаторами (сложность, выбор оппонента, лимит времени, тип задания).
  - Победителем должен быть пользователь, который верно решил задачу и затратил на это меньше времени.
  - Пользователь должен иметь возможность отправлять приглашение на игру другим пользователям.
  - Пользователь должен иметь возможность просматривать и сортировать таблицу лидеров (по рейтингу, количеству игр и т.д.).
  - Пользователь должен иметь возможность организовывать турниры и создавать турнирные сетки.
  - Пользователь должен иметь возможность просматривать историю своих игр и турниров.
  - Пользователь должен иметь возможность просматривать повторы своих игр.
  - Пользователь должен иметь возможность просматривать статистику по играм, турнирам и игрокам.
  - Пользователь должен иметь возможность просматривать код соперника после игры.
  - Пользователь должен иметь возможность сдаться, сбросить код или проверить решение в терминале.
  - Пользователь должен иметь возможность сыграть реванш.
  - На сайте должен быть чат и возможность отправлять личные сообщения другим игрокам.
  - На сайте должен быть выбор языков интерфейса.
  - На сайте должна быть возможность восстановления пароля.
  - На сайте должен быть выбор языка программирования и языка задачи.
  - На сайте должна быть возможность добавлять новые задания.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Пользователь должен иметь возможность сыграть пробную игру без регистрации.
  - Пользователь может находиться только в одном поединке одновременно.
  - Пользователи должны иметь возможность просматривать игры других пользователей онлайн.
  - У зрителей не должно быть возможности писать код и вносить изменения в терминалы участников игры.
  - Участник игры не может писать код в терминале соперника и изменять его.
  - На сайте должна быть реализована возможность проверки правильности кода посредством встроенного компилятора.
  - На сайте должна быть реализована система рейтинга игроков.
  - На сайте, в редакторе кода должна быть возможность смены темы.
  - На сайте должна быть возможность сортировки игр по тегам и уровню сложности.
